<?xml version="1.0" encoding="utf-8" ?>
<!-- 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License.
-->
<description xmlns="http://www.w3.org/ns/wsdl"
	targetNamespace="http://ws.apache.woden/endpoint"
	xmlns:tns="http://ws.apache.woden/endpoint"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:wsoap= "http://www.w3.org/ns/wsdl/soap"
    xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope"
    xmlns:ghns = "urn:ghns"
	xsi:schemaLocation=
	    "http://www.w3.org/ns/wsdl http://www.w3.org/ns/wsdl/wsdl20.xsd 
	    http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">

	<documentation>
	    Used by SOAPBindingFaultReferenceExtensionsTest to test the SOAPBindingFaultReferenceExtensions implementation.
	</documentation>

	<interface name="interface1">
        <fault name = "invalidDataFault"
               element = "ghns:invalidDataError" />
        <operation name="opCheckAvailability">
            <infault ref="tns:invalidDataFault" messageLabel="In"/>
            <outfault ref="tns:invalidDataFault" messageLabel="Out"/>
        </operation>
         
	</interface>
	
	<binding name="binding1"
	  interface="tns:interface1"
	  type="http://www.w3.org/ns/wsdl/soap">

        <operation ref="tns:opCheckAvailability">

            <infault ref="tns:invalidDataFault" messageLabel="In">
                <documentation>Test that 2 SOAPModule objects are created</documentation>
                <wsoap:module ref="urn:ccc" required="true" />
                <wsoap:module ref="urn:ddd" required="false" />
            </infault>
            
            <outfault ref="tns:invalidDataFault" messageLabel="Out">
                <documentation>Test that 1 SOAPModule objects are created</documentation>
                <wsoap:module ref="urn:eee" required="false" />
            </outfault>
            
       </operation>
        
	</binding>
	
	<service name="service1" interface="tns:interface1" />
	
</description>