<?xml version="1.0" encoding="utf-8" ?>
<!-- 
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 * 
 *     http://www.apache.org/licenses/LICENSE-2.0 
 * 
 * Unless required by applicable law or agreed to in writing, software 
 * distributed under the License is distributed on an "AS IS" BASIS, 
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. 
 * See the License for the specific language governing permissions and 
 * limitations under the License.
-->
<description xmlns="http://www.w3.org/ns/wsdl"
	targetNamespace="http://ws.apache.woden/endpoint"
	xmlns:tns="http://ws.apache.woden/endpoint"
	xmlns:xs="http://www.w3.org/2001/XMLSchema"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:wsoap= "http://www.w3.org/ns/wsdl/soap"
    xmlns:soap-env="http://www.w3.org/2003/05/soap-envelope"
    xmlns:whttp= "http://www.w3.org/ns/wsdl/http"
    xmlns:ghns = "urn:ghns"
	xsi:schemaLocation=
	    "http://www.w3.org/ns/wsdl http://www.w3.org/ns/wsdl/wsdl20.xsd 
	    http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">

	<documentation>
	    Used by SOAPBindingOperationExtensionsTest to test the SOAPBindingOperationExtensions implementation.
	</documentation>

	<interface name="interface1" />
	
	<binding name="binding1"
	  interface="tns:interface1"
	  type="http://www.w3.org/ns/wsdl/soap"
	  wsoap:version="1.2"
	  wsoap:protocol="http://www.w3.org/2003/05/soap/bindings/HTTP/">

        <operation
          wsoap:mep="urn:mep"
          wsoap:action="urn:action"
	      whttp:queryParameterSeparator="$">
            <documentation>Test that mep and action attributes are parsed correctly.</documentation>
            <documentation>Test that 1 SOAPModule object is parsed.</documentation>
            <documentation>Test that query paramater separator is parsed correctly.</documentation>
            <wsoap:module ref="urn:ccc" required="true" />
        </operation>
        
	</binding>
	
	<binding name="binding2"
	  interface="tns:interface1"
	  type="http://www.w3.org/ns/wsdl/soap"
	  wsoap:version="1.1"
	  wsoap:protocol="http://www.w3.org/2006/01/soap11/bindings/HTTP/">

        <operation
          wsoap:mep="urn:mep"
          wsoap:action="urn:action">
            <documentation>Test that mep and action attributes are parsed correctly.</documentation>
            <documentation>Test that 1 SOAPModule object is parsed.</documentation>
            <documentation>Test that query paramater separator defaults to null if omitted from the WSDL.</documentation>
            <wsoap:module ref="urn:ccc" required="true" />
        </operation>
        
	</binding>
	
	<service name="service1" interface="tns:interface1" />
	
</description>